apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular-deployment
          image: junyoun98/go-angular-nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
